### ISSUE TITLE
404 on API

### ISSUE THREAD

**Issue by biddster** [Alheimsins/leaf-connect#6]
The API endpoint has changed to: 

`https://gdcportalgw.its-mo.com/api_v210707_NE/gdc/`

I edited the code in my node_modules and tested it and it's fine. 

Found the new endpoint via:

https://github.com/Tobiaswk/dartcarwings/blob/master/lib/src/carwings_session.dart

**Comment by maccyber** [comment]
Ah, thanks a lot @biddster. Was looking for this yesterday.

Updated!
